### ISSUE TITLE
在三星手机上报错了

### ISSUE THREAD

**Issue by JeromeLydia** [smewise/Camera2#12]
IllegalArgumentException while invoking public abstract void android.hardware.camera2.CameraCaptureSession$StateCallback.onConfigured(android.hardware.camera2.CameraCaptureSession)
    java.lang.IllegalArgumentException: CaptureRequest contains unconfigured Input/Output Surface!
        at android.hardware.camera2.CaptureRequest.convertSurfaceToStreamId(CaptureRequest.java:582)
        at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:938)
        at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:984)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:238)
        at com.zoneyet.gaga.me.transmachine.photorecognition.camera2.manager.Session.sendRepeatingRequest(Session.java:111)
        at com.zoneyet.gaga.me.transmachine.photorecognition.camera2.manager.CameraSession.sendPreviewRequest(CameraSession.java:184)
        at com.zoneyet.gaga.me.transmachine.photorecognition.camera2.manager.CameraSession.access$300(CameraSession.java:30)
        at com.zoneyet.gaga.me.transmachine.photorecognition.camera2.manager.CameraSession$2.onConfigured(CameraSession.java:306)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
        at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)

**Comment by JeromeLydia** [comment]
请问产生这个问题的原因是什么那？
